import type { HelpNeed, HelpPoint, PointComment } from '../src/types';

/**
 * Datos semilla (fallback) usados cuando Supabase no está configurado o no
 * devuelve filas: mantienen la app utilizable en modo 100% local.
 * Las rutas de imagen apuntan a `public/images` para que funcionen también
 * en el build de producción.
 */
export const INITIAL_HELP_POINTS: HelpPoint[] = [
  {
    id: 'cali-acopio-1',
    name: 'Centro de Acopio Central - Parque Panamericano (Las Banderas)',
    category: 'acopio',
    lat: 3.4315,
    lng: -76.5385,
    address: 'Calle 5 con Carrera 34, Parque Panamericano',
    barrio: 'San Fernando',
    comuna: 'Comuna 19',
    phone: '+57 315 489 2210',
    whatsapp: '573154892210',
    contactPerson: 'Carlos Mario Giraldo (Defensa Civil)',
    description:
      'Punto estratégico de recepción masiva de víveres, agua embotellada, frazadas y kits de aseo con camiones de distribución hacia comunas de ladera.',
    schedule: 'Lunes a Domingo: 7:00 AM - 8:00 PM',
    status: 'abierto',
    urgentItems: ['Agua potable', 'Enlatados con abre fácil', 'Cobijas térmicas', 'Kits de aseo personal'],
    capacity: 'Almacenamiento alto (capacidad de camiones 10T)',
    verified: true,
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-26T14:30:00Z',
  },
  {
    id: 'cali-vet-1',
    name: 'Albergue y Clínica Huellitas Cali Solidaria',
    category: 'veterinaria',
    lat: 3.4475,
    lng: -76.5412,
    address: 'Carrera 10 # 2-45, Colina de San Antonio',
    barrio: 'San Antonio',
    comuna: 'Comuna 3',
    phone: '+57 318 642 9011',
    whatsapp: '573186429011',
    contactPerson: 'Dra. Marcela Restrepo (Médica Veterinaria)',
    description:
      'Atención médica veterinaria prioritaria para perros y gatos rescatados, curaciones de emergencia, vacunación y punto de recepción de concentrado.',
    schedule: 'Urgencias 24 Horas',
    status: 'alta_demanda',
    urgentItems: ['Concentrado perros y gatos', 'Gasas estériles', 'Suero fisiológico', 'Antibióticos veterinarios'],
    capacity: '42 caninos / 28 felinos albergados',
    verified: true,
    createdAt: '2026-09-21T10:00:00Z',
    updatedAt: '2026-09-26T16:00:00Z',
  },
  {
    id: 'cali-salud-1',
    name: 'Hospital Universitario del Valle (HUV) - Urgencias Adultos y Pediatría',
    category: 'salud',
    lat: 3.43,
    lng: -76.543,
    address: 'Calle 5 # 36-08',
    barrio: 'San Fernando',
    comuna: 'Comuna 19',
    phone: '+57 602 620 6000',
    whatsapp: '573207881122',
    contactPerson: 'Dra. Elena Mosquera (Jefatura de Urgencias)',
    description:
      'Principal centro hospitalario de trauma y alta complejidad del suroccidente colombiano. Punto de recepción de donación voluntaria de sangre tipo O- y A+.',
    schedule: 'Urgencias 24 Horas',
    status: 'abierto',
    urgentItems: ['Donantes de sangre O- y A+', 'Kits hospitalarios', 'Soluciones parenterales'],
    capacity: 'Nivel 4 de Complejidad - Urgencias habilitadas',
    verified: true,
    createdAt: '2026-09-18T00:00:00Z',
    updatedAt: '2026-09-26T15:00:00Z',
  },
  {
    id: 'cali-albergue-1',
    name: 'Albergue Comunitario Refugio San Bosco',
    category: 'albergue',
    lat: 3.442,
    lng: -76.531,
    address: 'Carrera 13 # 9-22',
    barrio: 'San Bosco',
    comuna: 'Comuna 9',
    phone: '+57 312 890 3344',
    whatsapp: '573128903344',
    contactPerson: 'Hermano Gabriel Peña (Pastoral Social)',
    description:
      'Refugio comunitario temporal con capacidad para albergar familias en condición de vulnerabilidad, cocina comunitaria con 250 raciones calientes diarias.',
    schedule: 'Ingreso 8:00 AM - 7:00 PM (Recepción 24h para emergencias)',
    status: 'alta_demanda',
    urgentItems: ['Colchonetas impermeables', 'Leche en polvo infantil', 'Pañales etapas 2 y 3', 'Arroz y granos'],
    capacity: '85 personas (72 ocupadas actualmente)',
    verified: true,
    createdAt: '2026-09-19T09:00:00Z',
    updatedAt: '2026-09-26T12:00:00Z',
  },
  {
    id: 'cali-acopio-2',
    name: 'Punto Móvil de Acopio Norte - Parque de la Música / Chipichape',
    category: 'acopio',
    lat: 3.472,
    lng: -76.528,
    address: 'Avenida 6N con Calle 35N',
    barrio: 'Granada / Santa Mónica Residencial',
    comuna: 'Comuna 2',
    phone: '+57 317 554 9901',
    whatsapp: '573175549901',
    contactPerson: 'Luisa Fernanda Soto (Red Caleña Voluntaria)',
    description:
      'Punto de recolección de donaciones para el norte de la ciudad. Camión de acopio habilitado con báscula y clasificación de paquetes de socorro.',
    schedule: 'Lunes a Sábado: 8:00 AM - 6:00 PM',
    status: 'abierto',
    urgentItems: [
      'Alimentos no perecederos',
      'Ropa en buen estado para niños',
      'Zapatos tallas 24 a 38',
      'Agua potable',
    ],
    capacity: 'Camión furgón mediano para traslados diarios',
    verified: true,
    createdAt: '2026-09-22T08:30:00Z',
    updatedAt: '2026-09-26T11:00:00Z',
  },
];

export const INITIAL_HELP_NEEDS: HelpNeed[] = [
  {
    id: 'need-1',
    title: 'Cobijas térmicas y agua potable para familias en Comuna 20 (Siloé)',
    description:
      'Debido a las fuertes lluvias de la madrugada, 14 familias del sector La Estrella requieren apoyo inmediato con cobijas secas, agua potable y colchonetas.',
    category: 'albergue',
    urgency: 'alta',
    barrio: 'Siloé (Sector La Estrella)',
    contactName: 'Jeison Trujillo',
    contactPhone: '+57 314 782 1190',
    items: ['14 colchonetas', '30 cobijas térmicas', '20 pacas de agua potable', 'Kits de aseo'],
    status: 'activa',
    supportersCount: 18,
    createdAt: '2026-09-26T06:30:00Z',
    imageUrl: '/images/volunteer_aid_boxes_1790469956879.jpg',
  },
  {
    id: 'need-2',
    title: 'Concentrado urgente para 42 perritos rescatados en San Antonio',
    description:
      'El refugio Huellitas Cali Solidaria cuenta con raciones únicamente para 24 horas. Solicitamos donaciones de bultos de comida para perro cachorro y adulto.',
    category: 'veterinaria',
    urgency: 'alta',
    barrio: 'San Antonio',
    contactName: 'Dra. Marcela Restrepo',
    contactPhone: '+57 318 642 9011',
    items: ['Bultos concentrado Dog Chow / Ringo / Pedigree', 'Pipetas antipulgas', 'Toallas limpias'],
    status: 'activa',
    supportersCount: 34,
    createdAt: '2026-09-26T08:15:00Z',
    imageUrl: '/images/vet_animal_care_1790469966961.jpg',
  },
  {
    id: 'need-3',
    title: 'Apoyo para Olla Comunitaria en Polideportivo Los Chorros',
    description:
      'Estamos cocinando 300 almuerzos comunitarios diarios para niños y abuelos de Meléndez y Los Chorros. Necesitamos granos secos y verduras frescas.',
    category: 'acopio',
    urgency: 'media',
    barrio: 'Los Chorros / Meléndez',
    contactName: 'Amparo Cuero',
    contactPhone: '+57 321 908 6612',
    items: ['Arroz (3 bultos)', 'Frijol y lenteja', 'Plátano verde', 'Aceite vegetal'],
    status: 'en_proceso',
    supportersCount: 22,
    createdAt: '2026-09-25T14:00:00Z',
    imageUrl: '/images/volunteer_aid_boxes_1790469956879.jpg',
  },
];

export const INITIAL_COMMENTS: PointComment[] = [
  {
    id: 'comm-1',
    pointId: 'cali-acopio-1',
    userId: 'usr-101',
    userName: 'Mariana Caicedo',
    userRole: 'voluntario',
    userBarrio: 'San Fernando',
    comment:
      'Llegó un camión con 50 pacas de agua potable a las 3:00 PM. Por favor prioricen donaciones de cobijas y alimentos no perecederos.',
    createdAt: '2026-09-26T15:10:00Z',
  },
  {
    id: 'comm-2',
    pointId: 'cali-acopio-1',
    userId: 'usr-102',
    userName: 'Javier Osorio',
    userRole: 'ciudadano',
    userBarrio: 'El Peñón',
    comment:
      'Punto muy organizado por la Defensa Civil y brigadistas. Reciben donaciones rápido y entregan constancia física.',
    createdAt: '2026-09-26T16:20:00Z',
  },
  {
    id: 'comm-3',
    pointId: 'cali-vet-1',
    userId: 'usr-103',
    userName: 'Dra. Claudia Varela',
    userRole: 'voluntario',
    userBarrio: 'San Antonio',
    comment: 'Recibimos 3 cachorritos rescatados de ladera. Ya fueron revisados y medicados. Agradecemos gasas y suero.',
    createdAt: '2026-09-26T14:45:00Z',
  },
  {
    id: 'comm-4',
    pointId: 'cali-salud-1',
    userId: 'usr-104',
    userName: 'Carlos Andrés Holguín',
    userRole: 'coordinador',
    userBarrio: 'San Fernando',
    comment: 'Banco de sangre activo en el HUV. Se agradece donantes tipo O- y A+. Atención ágil en el piso 1.',
    createdAt: '2026-09-26T17:00:00Z',
  },
];
